Repository nickderobertis/cookiecutter-pypi-sphinx, pull requests merged in 2020-01, with the labels that each got.

#5 Add CI/CD to automatically open a PR in the generated project for changes in the cookiecutter
  README.md
  {{cookiecutter.repo_name}}/.github/workflows/template-update.yml
  {{cookiecutter.repo_name}}/conf.py
Labels: enhancement

#6 Get package docstrings included and give control over api docs template
  {{cookiecutter.repo_name}}/conf.py
  {{cookiecutter.repo_name}}/docsrc/Makefile
  {{cookiecutter.repo_name}}/docsrc/apidoc/templates/package.rst_t
Labels: enhancement

#7 Add default configuration for mypy
  {{cookiecutter.repo_name}}/conf.py
  {{cookiecutter.repo_name}}/mypy.ini
Labels: enhancement

#8 Fix bugs with checkout syntax and cron syntax in template update workflow
  {{cookiecutter.repo_name}}/.github/workflows/template-update.yml
Labels: bug

#9 Github Actions does not allow automated commits to update workflow files so raise an issue in generated repo when cookiecutter workflow file changes
  README.md
  {{cookiecutter.repo_name}}/.github/workflows/template-update.yml
  {{cookiecutter.repo_name}}/conf.py
  {{cookiecutter.repo_name}}/scripts/workflows-updated.sh
Labels: bug

#10 Add .vscode config to gitignore
  .gitignore
  {{cookiecutter.repo_name}}/.gitignore
Labels: enhancement

#11 Update README to better reflect cookiecutter steps
  README.md
Labels: documentation

#12 Add author to default README
  {{cookiecutter.repo_name}}/README.md
Labels: enhancement
